theme: jekyll-theme-minimal

permalink: /archive/:year/:month/:day/:title/
paginate: 20
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"
category_dir: categories

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
